### PR TITLE
Add debounce for power button, pull down gpioQ7 to unlock identify LED

### PR DESCRIPTION
**Pull request by Kenthliu**
1.GPIOQ7 make the LED GPIOH2 can not control when power on. So we need to pull down when init.
2. Add the debounce setting to avoid auto power on when power button to off.

Signed-off-by: Ken Liu ken.th.liu@foxconn.com

This change is [Reviewable](https://reviewable.io/reviews/openbmc/linux/78)

### CODE REVIEW

**Comment by shenki** [comment]
@Kenthliu can you please address the comments on the mailing list

**Comment by Kenthliu** [comment]
Is this OK?
Thanks.

**Comment by Kenthliu** [comment]
@shenki I a little confuse about the mailing list system. I already register my mail to the system (ken.th.liu@foxconn.com). But there is no reply option in the page https://lists.ozlabs.org/pipermail/openbmc/2016-May/002853.html. How can I response? 
Thanks.

**Comment by shenki** [comment]
Did you receive a mail `[PATCH linux] Add debounce for power button, pull down gpioQ7 to unlock identify LED` from joel@jms.id.au?

I just re-sent it to you

**Comment by Kenthliu** [comment]
I receive the mail from joel.stan@gmail.com. Not from  joel@jms.id.au.
Thanks.

**Pull request closed without merging**
